### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by zliubabalala** [allenai/allennlp#1377]
Hi,

When I try to follow the tutorial to train a simple tagger model. I got errors like:

Traceback (most recent call last):                                                                                                                                                            
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                   
    "__main__", mod_spec)                                                                                                                                                                     
  File "/usr/nic/apps/python_data_analytics/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code                                                                                              
    exec(code, run_globals)                                                                                                                                                                   
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>                                                           
    main(prog="allennlp")                                                                                                                                                                     
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main                                                 
    args.func(args)                                                                                                                                                                           
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args                                  
    args.recover)                                                                                                                                                                             
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file                                  
    return train_model(params, serialization_dir, file_friendly_logging, recover)                                                                                                             
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/commands/train.py", line 296, in train_model                                            
    metrics = trainer.train()                                                                                                                                                                 
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 679, in train                                                
    train_metrics = self._train_epoch(epoch)                                                                                                                                                  
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 463, in _train_epoch                                         
    loss = self._batch_loss(batch, for_training=True)                                                                                                                                         
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 398, in _batch_loss                                          
    output_dict = self._model(**batch)                                                                                                                                                        
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__                                               
    result = self.forward(*input, **kwargs)                                                                                                                                                   
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/models/simple_tagger.py", line 99, in forward                                           
    encoded_text = self.encoder(embedded_text_input, mask)                                                                                                                                    
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py", line 83, in forward
    self.sort_and_run_forward(self._module, inputs, mask, hidden_state)
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/allennlp/modules/encoder_base.py", line 116, in sort_and_run_forward
    module_output, final_states = module(packed_sequence_input, initial_states)
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 323, in forward
    return func(input, *fargs, **fkwargs)
  File "/lstr/home/liuz2/Py_Work/NLP_Study/AllenNLP_tutorial/env/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 287, in forward
    dropout_ts)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

And I have tested a simple RNN in Pytorch. It works. So is this a bug in AllenNLP?  Anyone have met the same issue? Any comment is appreciated.

**Comment by nelson-liu** [comment]
If I recall correctly, there is a problem with Pytorch 0.3.1 and the particular version of CUDNN used to build the package with CUDA 8.0. The workarounds are to install 9.1 version of Pytorch or to upgrade to 0.4.0 (which we made a new release today to support, so upgrading to the latest version of AllenNLP should solve your problem).

The error affects LSTM but not RNN, hence why simple rnn works.

Let me know if that doesn’t fix it.

**Comment by zliubabalala** [comment]
nelson-liu,

Thanks a lot for your comment! I will try you solution and let you know if the problem is fixed.

**Comment by zliubabalala** [comment]
nelson-liu,

I have installed the new version AllenNLP and updated my Pytorch to verion 0.4.0.. But I got the same error as before. I am using cuda 9.1 and cudnn 7.0. 

I also have tested rnn and lstm in Pythorch. They work well.  So do you have any other thoughts that may cause this problem?

**Comment by nelson-liu** [comment]
do you have a script i can run to reproduce your error?

**Comment by zliubabalala** [comment]
@nelson-liu  I am just following the tutorial to run this command: 
allennlp train getting_started/simple_tagger.json --serialization getting_started/simple_tagger_cuda

**Comment by nelson-liu** [comment]
unfortunately, I can't reproduce your error when running that command :( This feels like an issue with your installation of cuda / cudnn.

maybe try:

```
rm -rf ~/.nv
```

and rebooting?

**Comment by zliubabalala** [comment]
@nelson-liu I will try. Thanks a lot!

**Comment by nelson-liu** [comment]
are you using conda, by the way? i'll be releasing a conda build for the latest version of allennlp (0.5.1) in a bit, and that should give you a clean installation of cudnn and cuda.

**Comment by zliubabalala** [comment]
@nelson-liu rm -rf ~/.nv doesn't work for my system. If you didn't see the same issue then it might be just a problem in my system. I will dig more to see if I can fix the problem. 

I haven't used conda yet. I'd like to try it later on. Thank you very much.

**Comment by zliubabalala** [comment]
@nelson-liu I have updated my system to using cudnn 7.1.2  then the problem is solved. Thanks a lot for your help. I will close this issue.

**Comment by nelson-liu** [comment]
great to hear, thanks for updating w/ what worked for you.

**Comment by zpaines** [comment]
I'm having the same issue on cudnn version 7102 (according to `torch.backends.cudnn.version()`). I'm using `elmoEmbedder`'s `embed_batch`. The error only appears for larger batch sizes on a single specific input. I'm on cuda version `7.5.17`, and I'm using the allennlp conda environment specified [here](https://github.com/allenai/allennlp/blob/v0.6.1/README.md). I've attached the output of `pip freeze`, run from within the `allennlp` conda environment. 
[deps.txt](https://github.com/allenai/allennlp/files/2381354/deps.txt)

**Comment by zpaines** [comment]
If I increase the batch size passed into `embed_sentences` I start the see the error more frequently.

**Comment by zpaines** [comment]
@nelson-liu any insight into this? Is this an issue with my environment or some kind of compatibility problem in allennlp?

**Comment by nelson-liu** [comment]
oops, sorry for the lack of response. Maybe you can open a new issue with the traceback and i can take a look?

**Comment by zpaines** [comment]
Alright will do when I get a chance. Thanks!

**Comment by zpaines** [comment]
@nelson-liu opened [here](https://github.com/allenai/allennlp/issues/1791). Thanks!
