### ISSUE TITLE
Train bidaf with default setting, occur cuda runtime error (an illegal memory access)

### ISSUE THREAD

**Issue by DongjunLee** [allenai/allennlp#1475]
**Describe the bug**

I just start training bidaf with default setting.

**To Reproduce**
Steps to reproduce the behavior

1. clone allennlp repository.
3. set cuda_device id.
2. ```allennlp train training_config/bidaf.json -s bidaf_path```

**Expected behavior**

start trainining process.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: I installed from master
 - PyTorch version: 0.4.0

**Additional context**

This is a error message.

```
  0%|          | 0/2190 [00:00<?, ?it/s]2018-07-11 14:51:41,849 - INFO - allennlp.training.trainer - Training
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=339 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/home1/irteam/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home1/irteam/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home1/irteam/users/dongjun/allennlp/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/commands/train.py", line 103, in train_model_from_args
    args.recover)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/commands/train.py", line 133, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/commands/train.py", line 322, in train_model
    metrics = trainer.train()
  File "/home1/irteam/users/dongjun/allennlp/allennlp/training/trainer.py", line 708, in train
    train_metrics = self._train_epoch(epoch)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/training/trainer.py", line 481, in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/training/trainer.py", line 416, in _batch_loss
    output_dict = self._model(**batch)
  File "/home1/irteam/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/models/reading_comprehension/bidaf.py", line 241, in forward
    passage_lstm_mask))
  File "/home1/irteam/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py", line 83, in forward
    self.sort_and_run_forward(self._module, inputs, mask, hidden_state)
  File "/home1/irteam/users/dongjun/allennlp/allennlp/modules/encoder_base.py", line 92, in sort_and_run_forward
    num_valid = torch.sum(mask[:, 0]).int().item()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:339
```

**Comment by DeNeutoy** [comment]
It looks like you have a problem with CUDNN. Can you reproduce it by running inside of one of our released Docker images?

**Comment by DongjunLee** [comment]
That's right. There is a problem with CUDNN.
Thanks for your help. :)

**Comment by j6mes** [comment]
Which version of CuDNN were you using? I'm having similar issues on text_field_embedder using CuDNN 7.0.5

**Comment by playma** [comment]
How did you solve it?

**Comment by schmmd** [comment]
@DeNeutoy the CUDNN_STATUS_EXECUTION_FAILED is the error I'm getting on `allennlp-server4.corp`

**Comment by schmmd** [comment]
I think we're having this issue because we're running on a server with CUDA 10.1.  I'm able to work around this by installing a pytorch explicitly for 10.0 in a CUDA 10.0 environment.

### Using Conda

```
conda create -n allennlp python=3.6
conda activate allennlp
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
pip install allennlp
allennlp evaluate https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-dev-v1.1.json --cuda-device 0
```

### Using Docker
```
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
  
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         ca-certificates \
         python3-setuptools \
         python3.6-dev \
         python3-pip && \
     rm -rf /var/lib/apt/lists/*

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PATH /opt/conda/bin:/usr/local/nvidia/bin/:$PATH
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN pip3 install wheel
RUN pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
RUN pip3 install allennlp
```

Run using:

```
sudo docker build -t allennlp .
sudo docker run --runtime=nvidia allennlp allennlp evaluate https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-dev-v1.1.json --cuda-device 0
```

**Comment by amarasovic** [comment]
I followed the given steps @schmmd, but I have to install `allennlp` from master which unfortunately reinstalls `torch` that is compiled against cuda `9.0.176`. This is fixed by installing torch compiled against cuda 10 after installing `allennlp`.

Here are my instructions: 

```
conda create -n allennlp python=3.6
conda activate allennlp
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

pip install git+https://github.com/allenai/allennlp.git@master

pip install -U https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl`
```
