### ISSUE TITLE
Could the latest version of allennlp run on RTX 3090?

### ISSUE THREAD

**Issue by yipliu** [allenai/allennlp#4845]
When I create a conda env python=3.8.5, allennlp=1.2.2, I cannot find any version of cudatoolkit. Is this right? 
   And, when I run **allennlp test-install**, I get this:
    - INFO - allennlp.commands.test_install - AllenNLP version 1.2.2 installed to 
   
    - INFO - allennlp.commands.test_install - Cuda devices available: 1

And when I run a example, I get this error:
    - RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by epwalsh** [comment]
See https://github.com/pytorch/pytorch/issues/31285#issuecomment-739139454. You may need to install torch differently.

**Comment by yipliu** [comment]
> See [pytorch/pytorch#31285 (comment)](https://github.com/pytorch/pytorch/issues/31285#issuecomment-739139454). You may need to install torch differently.

Hi, epwalsh
I did a test about the env installation  based on RTX 3090
- First, I install pytorch=1.7 with cudatoolkit=11.0 according to the official website of Pytorch
- Then, I install allennlp and anllennlp-model
- Last, I run a example with cuda_device = 0
Luckly, the code work well on RTX 3090 this time.

For the result of "allennlp test-install",  there is no difference between my two different envs, especially "Cuda devices available: 1". However, this first env cannot work well on RTX 3090

**Comment by KaiserWhoLearns** [comment]
Using RTX3090, too. I experienced the same error when invoking any method with cuda after installing allennlp/allennlp-models. I am not sure if the installation caused the problem (may override my previous installation of CUDA 11.1?), but in case it may help anyone having the same error in the same scenario.

Roll back(or maybe upgrade?) my pytorch and cuda to the newest one on [their past release](https://pytorch.org/get-started/previous-versions/) solved my problem.
